/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  MarketStoreUtilsTest,
  MarketStoreUtilsTestInterface,
} from "../../../contracts/test/MarketStoreUtilsTest";

const _abi = [
  {
    inputs: [],
    name: "getEmptyMarket",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "marketToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "indexToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "longToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortToken",
            type: "address",
          },
        ],
        internalType: "struct Market.Props",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract DataStore",
        name: "dataStore",
        type: "address",
      },
      {
        internalType: "address",
        name: "key",
        type: "address",
      },
    ],
    name: "removeMarket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract DataStore",
        name: "dataStore",
        type: "address",
      },
      {
        internalType: "address",
        name: "key",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "marketToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "indexToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "longToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortToken",
            type: "address",
          },
        ],
        internalType: "struct Market.Props",
        name: "market",
        type: "tuple",
      },
    ],
    name: "setMarket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061037c806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80630f7c8c3a146100465780638593caac1461005b578063b8f1289114610079575b600080fd5b6100596100543660046101d2565b61008c565b005b6100636100fc565b60405161007091906102cc565b60405180910390f35b6100596100873660046102e0565b610111565b604051636a207dff60e01b815273__$ff439aa65a80c9eec648f15db20b189505$__90636a207dff906100c790869086908690600401610319565b60006040518083038186803b1580156100df57600080fd5b505af41580156100f3573d6000803e3d6000fd5b50505050505050565b610104610188565b61010c610188565b919050565b60405163b4fd626560e01b81526001600160a01b0380841660048301528216602482015273__$ff439aa65a80c9eec648f15db20b189505$__9063b4fd62659060440160006040518083038186803b15801561016c57600080fd5b505af4158015610180573d6000803e3d6000fd5b505050505050565b60408051608081018252600080825260208201819052918101829052606081019190915290565b6001600160a01b03811681146101c457600080fd5b50565b803561010c816101af565b600080600083850360c08112156101e857600080fd5b84356101f3816101af565b93506020850135610203816101af565b92506080603f198201121561021757600080fd5b50604051608081016001600160401b038111828210171561024857634e487b7160e01b600052604160045260246000fd5b8060405250610259604086016101c7565b8152610267606086016101c7565b6020820152610278608086016101c7565b604082015261028960a086016101c7565b6060820152809150509250925092565b80516001600160a01b03908116835260208083015182169084015260408083015182169084015260609182015116910152565b608081016102da8284610299565b92915050565b600080604083850312156102f357600080fd5b82356102fe816101af565b9150602083013561030e816101af565b809150509250929050565b6001600160a01b0384811682528316602082015260c0810161033e6040830184610299565b94935050505056fea264697066735822122041ce49406be27fd5917bb252566fcc4c661d559ee1129c073d570ba2f5abf15c64736f6c63430008100033";

type MarketStoreUtilsTestConstructorParams =
  | [
      linkLibraryAddresses: MarketStoreUtilsTestLibraryAddresses,
      signer?: Signer
    ]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MarketStoreUtilsTestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => {
  return (
    typeof xs[0] === "string" ||
    (Array.isArray as (arg: any) => arg is readonly any[])(xs[0]) ||
    "_isInterface" in xs[0]
  );
};

export class MarketStoreUtilsTest__factory extends ContractFactory {
  constructor(...args: MarketStoreUtilsTestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      const [linkLibraryAddresses, signer] = args;
      super(
        _abi,
        MarketStoreUtilsTest__factory.linkBytecode(linkLibraryAddresses),
        signer
      );
    }
  }

  static linkBytecode(
    linkLibraryAddresses: MarketStoreUtilsTestLibraryAddresses
  ): string {
    let linkedBytecode = _bytecode;

    linkedBytecode = linkedBytecode.replace(
      new RegExp("__\\$ff439aa65a80c9eec648f15db20b189505\\$__", "g"),
      linkLibraryAddresses[
        "contracts/market/MarketStoreUtils.sol:MarketStoreUtils"
      ]
        .replace(/^0x/, "")
        .toLowerCase()
    );

    return linkedBytecode;
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MarketStoreUtilsTest> {
    return super.deploy(overrides || {}) as Promise<MarketStoreUtilsTest>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MarketStoreUtilsTest {
    return super.attach(address) as MarketStoreUtilsTest;
  }
  override connect(signer: Signer): MarketStoreUtilsTest__factory {
    return super.connect(signer) as MarketStoreUtilsTest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MarketStoreUtilsTestInterface {
    return new utils.Interface(_abi) as MarketStoreUtilsTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MarketStoreUtilsTest {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MarketStoreUtilsTest;
  }
}

export interface MarketStoreUtilsTestLibraryAddresses {
  ["contracts/market/MarketStoreUtils.sol:MarketStoreUtils"]: string;
}
